language: python
dist: xenial
matrix:
  include:
    # FIXME: `pip install PySide` fail
    # - python: '2.7'
    #   env: TOXENV=py27-PySide
    - python: '3.6'
      env: TOXENV=py36-PySide2
    - python: '3.6'
      env: TOXENV=py36-PyQt5
    - python: '3.7'
      env: TOXENV=py37-PySide2
    - python: '3.7'
      env: TOXENV=py37-PyQt5
install:
  - pip install tox
  - sudo apt-get update && sudo apt-get install ffmpeg
cache:
  - pip
before_script:
  - sudo -H pip2.7 install coscmd
  - coscmd config -a $COS_ID -s $COS_KEY -b codeclimate-report-1253052102 -r eu-frankfurt
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - xvfb-run tox
after_script:
  - ./cc-test-reporter format-coverage --output "coverage/codeclimate.$TRAVIS_JOB_NUMBER.json"
  - coscmd upload -r coverage /build-$TRAVIS_BUILD_NUMBER
  - coscmd download -r /build-$TRAVIS_BUILD_NUMBER coverage
  - ./cc-test-reporter sum-coverage --output - --parts 5 coverage/codeclimate.*.json | ./cc-test-reporter upload-coverage --input -
