language: python
python:
  - "2.7"
  - "3.6"
git:
    submodules: false
install:
  - /usr/bin/env python2.7 -m pip install coscmd
  - coscmd config -a $COS_ID -s $COS_KEY -b codeclimate-report-1253052102 -r ap-beijing 
  - yes "" | sudo add-apt-repository ppa:mc3man/trusty-media
  - sudo apt-get update
  - sudo apt-get install ffmpeg
  - ffmpeg -version
  - pip install pipenv
  - pipenv --version
  - pipenv install
  - pip install PySide || pip install PyQt5
  - pip install coverage
  - ls ./tests/resource
cache:
  - pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - xvfb-run pipenv run coverage run -m unittest discover -v -s ./tests -p test_*.py
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT