language: python
python:
  - "2.7"
  - "3.6"
git:
    submodules: false
install:
  - pip install pipenv
  - pipenv --version
  - pipenv install
  - pip install PySide || pip install PyQt5
  - pip install coverage
cache:
  - pip
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - xvfb-run pipenv run coverage run -m unittest discover -v -s ./tests -p test_*.py
after_script:
  - coverage xml
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT